version: '3.4'

services:
  app:
    build: .
    command: /bin/bash
    volumes:
      - .:/app
    network_mode: host
    privileged: true
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
